# Generated by Django 3.2.23 on 2024-04-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitycard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='identitycard',
            name='valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='有效期终止日'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='valid_to',
            field=models.DateField(blank=True, null=True, verbose_name='有效期终止日'),
        ),
    ]
