# Generated by Django 3.2.23 on 2024-04-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240424_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitycard',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='identitycard',
            name='valid_from',
            field=models.DateField(verbose_name='有效期起始日'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='valid_from',
            field=models.DateField(verbose_name='有效期起始日'),
        ),
    ]
